# Generated by Django 4.0.3 on 2022-04-07 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='rightAnswer',
        ),
    ]
