# Generated by Django 4.0.3 on 2022-04-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_questions_rightanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='rightAnswer',
            field=models.FloatField(blank=True, default=0, max_length=10),
            preserve_default=False,
        ),
    ]
